### ISSUE TITLE
I cannot use paper-dropdown-menu inside paper-step

### ISSUE THREAD

**Issue by fakiolinho** [patgmiller/paper-steps#23]
Unfortunately i cannot use `paper-dropdown-menu` element inside `paper-step`. Its options cannot get selected. Any ideas why this happens?

**Comment by patgmiller** [comment]
Thank you for using `paper-steps`. 

Can you create an example with JSbin to reproduce it? Is the `paper-steps` set to vertical or horizontal? Also, you might check if there are any elements with a higher `z-index` than your `paper-dropdown-menu` which might cause the element to be un-clickable.

**Comment by patgmiller** [comment]
@fakiolinho I have found the cause of this problem and will have a patch for it soon. Thanks for reporting the issue.
