### ISSUE TITLE
Use `cursor: pointer;` for elements that are clickable

### ISSUE THREAD

**Issue by ataylor32** [patgmiller/paper-steps#3]
Currently, some things that are clickable don't have `cursor: pointer;`, so the fact that they're clickable isn't as obvious as it should be.

**Comment by patgmiller** [comment]
This appears to be completed now, are there any other elements which should have the `cursor: pointer;` but do not?

**Comment by ataylor32** [comment]
I don't think so

**Comment by patgmiller** [comment]
Thanks, then we'll mark it as completed.
