### ISSUE TITLE
Not working in shadow DOM

### ISSUE THREAD

**Issue by manikandan0682** [patgmiller/paper-steps#30]
Hello,

I am new to polymer, trying to implement paper-steps for one of our requirement. This element is really awesome, but when I try add this element in Shadow Dom, it is not rendering correctly. Am I missing anything here? Your response is appreciated.

Thanks
Mani

**Comment by patgmiller** [comment]
Hello, no you're not missing anything,  I haven't made it shadow dom compatible yet. It is on my near to do list though. So currently it only uses shady dom.

**Comment by manikandan0682** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Thanks for the reply Patrick. 


Sent from Yahoo Mail for iPhone


On Friday, July 22, 2016, 3:30 PM, Patrick Miller <notifications@github.com> wrote:


Hello, no you're not missing anything, I haven't made it shadow dom compatible yet. It is on my near to do list though. So currently it only uses shady dom.

**Comment by patgmiller** [comment]
@manikandan0682 I have a branch, [paper-steps/shadow-dom](/patgmiller/paper-steps/tree/shadow-dom) which fixes this issue. The tests succeed locally in Chrome and Firefox, but they keep failing on Travis CI. Would you like to clone that branch and test it in your project to see if it works for you?

Thanks,
