### ISSUE TITLE
It's a problem with the stepper

### ISSUE THREAD

**Issue by juanmendez92** [patgmiller/paper-steps#33]
In a new update of Polymer elements, the paper-steps underwent a change.  Now all that is not within an iron-form will not be loaded in the DOM.

![paper steps demo](https://cloud.githubusercontent.com/assets/11398725/17752409/54274764-6491-11e6-8221-7200e9dbd1f9.png)

**Comment by patgmiller** [comment]
Please provide more details such as which Polymer release, which browser you tested in and any additional details necessary to reproduce the issue you're describing. A test example showing the issue in jsBin it CodePen would be appreciated.

Also, note `paper-steps` was designed specifically with form steps in mind and selects only content with `form[iron-form]`, so it could just be that. 

If you're looking for additional features then describe what you're hoping for like use cases etc.
